apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: xxx
spec:
  successfulJobsHistoryLimit: 1
  # UTC
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: athena
              image:  427794181662.dkr.ecr.ap-northeast-1.amazonaws.com/athena-client-go:v1
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: aws-access-key
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: aws-secret-key
                - name: S3_BUCKET
                  value: cyberbiz-athena-output
                - name: SLACK_WEBHOOK
                  value: xxx
              volumeMounts:
                - name: query
                  mountPath: /app/query.sql
                  subPath: query.sql
              resources:
                requests:
                  memory: 128Mi
                  cpu: 20m
          volumes:
            - name: query
              configMap:
                name: query

